### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'StatusIcon'

### ISSUE THREAD

**Issue by mxmilkiib** [pmrv/brightnessicon#2]
Trying on Arch atm;

```
/home/milk/src/brightnessicon/./brightnessicon:2: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
Traceback (most recent call last):
  File "/home/milk/src/brightnessicon/./brightnessicon", line 121, in <module>
    tray = Tray (o)
  File "/home/milk/src/brightnessicon/./brightnessicon", line 35, in __init__
    self.icon = Gtk.StatusIcon.new_from_file ("/usr/share/brightnessicon/icon.svg")
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'StatusIcon'
```

**Comment by pmrv** [comment]
What version of the `gtk3` package are you on?  I've just tried installing it with `1:3.24.30+62+g8d04980f38-2` and it works.  I just read that `Gtk.StatusIcon` is deprecated and gtk3 and removed in gtk4, so if you're already on gtk4 this might be the problem.

**Comment by pmrv** [comment]
Btw. to make sure you have the deps in your arch install with the provided `PKGBUILD`, i.e. copy it somewhere and then run `makepkg -si`, instead of running the script directly.
